// src/app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header"; // <-- 1. Import Header
import Footer from "@/components/layout/Footer"; // <-- 2. Import Footer
import { SanityLive } from "@/sanity/lib/live"; // <-- 3. Import SanityLive

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        {/* 4. Add a wrapping div for layout */}
        <div className="flex min-h-screen flex-col">
          <Header />
          {/* 5. Make children grow to fill space */}
          <main className="flex-1">{children}</main>
          <Footer />
        </div>
        
        {/* 6. Add Sanity visual editing component */}
        <SanityLive />
      </body>
    </html>
  );
}